version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: container-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123




  delivery-management:
    build:
      context: .
      dockerfile: Dockerfile
    image: deliverymanagement:latest
    container_name: deliverymanagement
    environment:
      SPRING_CONFIG_LOCATION: "file:/app/config/application.yml"
      HOSTNAME_MONGO: mongo
    ports:
      - "8080:2222"
    depends_on:
      - mongo
    volumes:
      - C:/sara/workspaceProjectIntellij/deliveryManagement/src/main/resources/application.yml:/app/config/application.yml

